{% set name = "groff" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://ftp.gnu.org/gnu/groff/groff-{{ version }}.tar.gz
    sha256: 6b9757f592b7518b4902eb6af7e54570bdccba37a871fddb2d30ae3863511c13
  - url: https://github.com/ArtifexSoftware/urw-base35-fonts/archive/20200910.tar.gz
    sha256: e0d9b7f11885fdfdc4987f06b2aa0565ad2a4af52b22e5ebf79e1a98abd0ae2f
    folder: urw-base35-fonts

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - make
    - automake
    - gawk
    - texinfo
    - pkg-config
    - flex
    - bison
    - ghostscript
    - netpbm
  host:
    - perl
    - libiconv  # [osx]
  run:
    - perl

test:
  commands:
    - eqn --version
    - grn --version
    - grodvi --version
    - groff --version
    - grolbp --version
    - grolj4 --version
    - grops --version
    - grotty --version
    - indxbib --version
    - post-grohtml --version
    - pre-grohtml --version
    - preconv --version
    - troff --version
    - chem --version
    - gperl --version
    - gpinyin --version
    # - groffer --version
    - grog --version
    - gropdf --version
    - neqn --version
    - nroff --version
    - test -f $PREFIX/bin/glilypond
    - test -f $PREFIX/bin/afmtodit

about:
  home: https://www.gnu.org/software/groff/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: 'Groff (GNU troff) is a typesetting system'
  description: |
    The Groff package contains programs for processing and formatting text.
  doc_url: https://www.gnu.org/software/groff/#documentation
  dev_url: http://git.savannah.gnu.org/cgit/groff.git

extra:
  recipe-maintainers:
    - nehaljwani
